name: Ō/RÁNJ
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44298
title: JŌ/RÁN + Ō/RÁNJ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e93900'
    - '#9c0900'
    - '#fefefa'
    - '#d3a7a0'
    - '#d8652f'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
