name: Ō/RÁNJ
favicon: null
layout_spectrum: 0.25445
typography_spectrum: 0.74547
title: JŌ/RÁN + Ō/RÁNJ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ababab'
    - '#d9d9d9'
    - '#696969'
    - '#dfc60c'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
